# Change these first
owner: aerolution # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Landing site
    url: https://katlyn.cloud
  - name: Giraffe API
    url: https://api.katlyn.cloud
  - name: Forum
    url: https://forum.katlyn.cloud
  - name: Private Image Host
    url: https://host.katlyn.cloud
  - name: Lain Discord Bot
    url: http://172.105.134.225:8000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.katlyn.cloud
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "This is a static status site for **katlyn.cloud.** Running on **upptime**."
  introMessage: Below are all status reports for katlyn.cloud domains.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
